revised test script; now more useful

diff --git a/test b/test
--- a/test
+++ b/test
@@ -10,8 +10,26 @@
 # Compile and check the error of each expected-to-fail test
 
 STOP="./stop.native"
+STOP_OPTION="-cff"
 TEST_FOLDER="tests"
 
 ulimit -t 30
 
-${STOP} ${TEST_FOLDER}/test-$1.stp
+# Exit script if there is no stop.native executable
+if [ ! -f ${STOP} ]; then
+	echo "${STOP} not found" 1>&2
+	exit 1
+fi
+
+if [ -f test-$1.stp ]; then
+	${STOP} ${STOP_OPTION} test-$1.stp && lli test-$1.ll
+	exit 0
+fi
+
+if [ -f ${TEST_FOLDER}/test-$1.stp ]; then
+	${STOP} ${STOP_OPTION} ${TEST_FOLDER}/test-$1.stp && lli test-$1.ll
+	exit 0
+fi
+
+echo "test-${1}.stp not found in /. or in /${TEST_FOLDER}/"
+exit 1
